spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/suitcase
    username: suitcase
    password: suitcase
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:main-changelog.xml
server:
  port: 9000
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
web-security:
  whitelist: /swagger-ui/**, /v3/api-docs/**, /webjars/**, /v1/authenticate
